Web_Plane/Models/ModelClass/DangKyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web_Plane.ViewModels
{
    public class DangKyViewModel
    {
        public char CCCD { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
    }
}

Web_Plane/Models/ModelClass/dangnhap.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web_Plane.Models.ModelClass
{
    public class dangnhap
    {
        public int CCCD { get; set; }
        public String Password { get; set; }
        public string Email { get; set; }
    }
}

Web_Plane/Controllers/Chucnang/ChucNangController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_Plane.Models;
using Web_Plane.Models.ModelClass;
using Web_Plane.ViewModels;

namespace Web_Plane.Controllers.Chucnang
{

    public class ChucNangController : Controller
    {
        DBMayBayEntities DBMayBayEntities = new DBMayBayEntities();
        // GET: ChucNang
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Dangnhap(dangnhap model)
        {
            // Kiểm tra đăng nhập cho admin
            if (model.Email == "admin@example.com" && model.Password == "1")
            {
                // Đăng nhập thành công với vai trò admin
                Session["IsAdmin"] = true;
                return RedirectToAction("Danhsachsanbay", "HomeAdmin", new { area = "Admin" });
                // return RedirectToAction("TrangChu", "Home");
            }
            var kh = DBMayBayEntities.KHACHHANGs.FirstOrDefault(k => k.Email == model.Email);
            if (kh != null)
            {
                bool isValid = VerifyPassword(model.Password, kh.Password);
                if (isValid)
                {
                    Session["TaiKhoan"] = kh;
                    Session["HoTen"] = kh.HoTen;
                    return RedirectToAction("TrangChu", "Home");
                }
                else
                {
                    ViewBag.ThongBao = "Mật khẩu không đúng !!";
                    return View();
                }
            }
            else
            {
                ViewBag.ThongBao = "Email không đúng !!";
                return View();
            }
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        // POST: DangKy
        // POST: ChucNang/DangKy
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangKy(KHACHHANG khachhang)
        {
            if (ModelState.IsValid)
            {
                // Kiểm tra CCCD trùng lặp
                var existingCCCD = DBMayBayEntities.KHACHHANGs.FirstOrDefault(kh => kh.CCCD == khachhang.CCCD);
                if (existingCCCD != null)
                {
                    ModelState.AddModelError("CCCD", "CCCD đã được sử dụng.");
                    Console.WriteLine("1");
                }

                // Kiểm tra email trùng lặp
                var existingEmail = DBMayBayEntities.KHACHHANGs.FirstOrDefault(kh => kh.Email == khachhang.Email);
                if (existingEmail != null)
                {
                    ModelState.AddModelError("Email", "Email đã được sử dụng.");
                    Console.WriteLine("2");
                }
                else
                {
                    DBMayBayEntities.Configuration.ValidateOnSaveEnabled = false;
                    khachhang.LoaiKH = "Thành viên";
                    khachhang.Password = HashPassword(khachhang.Password);
                    DBMayBayEntities.KHACHHANGs.Add(khachhang);
                    DBMayBayEntities.SaveChanges();
                    return RedirectToAction("DangNhap");
                }
            }

            // Nếu có lỗi, trả lại view đăng ký với các thông báo lỗi
            return View(khachhang);
        }


        [HttpGet]
        public ActionResult QuenMatKhau(string cccd) 
        {
            KHACHHANG kh = DBMayBayEntities.KHACHHANGs.FirstOrDefault(k => k.CCCD == cccd);
            return View(kh); 
        }
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult QuenMatKhau(string cccd)
        //{
        //    //if (ModelState.IsValid)
        //    //{

        //    //}
        //    return View();
        //}
        public ActionResult ThongTinChuyenBay()
        {
            var cb = DBMayBayEntities.CHUYENBAYs.ToList();
            return View(cb);
        }
        public ActionResult CacVe(string idcb)
        {
            List<VeMayBay> Dsachve = DBMayBayEntities.VeMayBays.Where(v => v.IDCB == idcb).ToList();
            if (Dsachve.Count > 0)
                ViewBag.DanhSachVeTitle = "Danh sách vé";
            else
                ViewBag.DanhSachVeTitle = "Danh sách vé";
            return View(Dsachve);
        }
        private string HashPassword(string password)
        {
            // Mã hóa mật khẩu bằng SHA256
            using (var sha256 = System.Security.Cryptography.SHA256.Create())
            {
                var bytes = System.Text.Encoding.UTF8.GetBytes(password);
                var hash = sha256.ComputeHash(bytes);
                var base64Hash = Convert.ToBase64String(hash);

                // Cắt ngắn hash để phù hợp với nvarchar(40)
                return base64Hash.Length > 40 ? base64Hash.Substring(0, 40) : base64Hash;
            }
        }

        private bool VerifyPassword(string enteredPassword, string storedHash)
        {
            // Băm mật khẩu đã nhập
            string enteredPasswordHash = HashPassword(enteredPassword);

            // So sánh hash của mật khẩu đã nhập với hash đã lưu trữ
            return enteredPasswordHash == storedHash;
        }


    }
}

Web_Plane/Views/Chucnang/CacVe.cshtml
@model IEnumerable<Web_Plane.Models.VeMayBay>

@{
    ViewBag.Title = "CacVe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CacVe</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MaVe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ChoNgoi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LoaiHanhLy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThanhTien)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IDCB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaLoaiVe)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaVe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ChoNgoi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LoaiHanhLy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ThanhTien)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IDCB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaLoaiVe)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

Web_Plane/Views/Chucnang/DangNhap.cshtml
@model Web_Plane.Models.ModelClass.dangnhap

@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Đăng nhập</title>
    <link href="~/Content/Picture/logomaybay.jpg" rel="icon" type="image/x-icon" />
    <link href="~/Content/css/DangNhap.css" rel="stylesheet" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    <div class="wrapper">
        @using (Html.BeginForm("Dangnhap", "ChucNang", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <h1>Đăng nhập</h1>
            <div class="input-box">
                @Html.TextBoxFor(m => m.Email, new { @placeholder = "Nhập Email", @required = "required", @class = "form-control" })
                <i class='bx bxs-user'></i>
            </div>
            <div class="input-box">
                @Html.PasswordFor(m => m.Password, new { @placeholder = "Nhập mật khẩu", @required = "required", @class = "form-control" })
                <i class='bx bxs-lock-alt'></i>
            </div>
            <div class="Quen_mat_khau">
                @Html.ActionLink("Quên mật khẩu", "QuenMatKhau", "ChucNang")
            </div>
            <button type="submit" class="btn_Dang_nhap">Đăng nhập</button>

            <div class="Dang_ky_tai_khoan">
                <label>
                    Bạn chưa có tài khoản?
                    @Html.ActionLink("Tạo tài khoản", "DangKy", "ChucNang")
                </label>
            </div>
        }
    </div>
</body>
</html>

Web_Plane/Views/Chucnang/Dangky.cshtml
@model Web_Plane.Models.KHACHHANG
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Picture/logomaybay.jpg" rel="icon" type="image/x-icon" />
    <title>Đăng ký</title>
    <link href="~/Content/css/DangKy.css" rel="stylesheet" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <div class="wrapper">
        @using (Html.BeginForm("DangKy", "ChucNang", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <h1>Đăng ký</h1>
            <div class="input-box">
                @Html.TextBoxFor(m => m.CCCD, new { @placeholder = "Nhập cccd", @type = "number", @required = "required", @autocomplete = "cccd" })
                <i class='bx bxs-id-card'></i>
            </div>
            <div class="input-box">
                @Html.TextBoxFor(m => m.HoTen, new { @placeholder = "Nhập họ và tên", @required = "required", @autocomplete = "name" })
                <i class='bx bxs-user'></i>
            </div>
            <div class="input-box">
                @Html.TextBoxFor(m => m.Sdt, new { @placeholder = "Nhập Số điện thoại của bạn", @required = "required", @autocomplete = "sdt" })
                <i class='bx bxs-user'></i>
            </div>
            <div class="input-box">
                @Html.TextBoxFor(m => m.Email, new { @placeholder = "Nhập Email của bạn", @type = "email", @required = "required", @autocomplete = "email" })
                <i class='bx bxs-envelope'></i>
            </div>
            <div class="input-box">
                @Html.PasswordFor(m => m.Password, new { @placeholder = "Nhập mật khẩu", @required = "required", @autocomplete = "new-password" })
                <i class='bx bxs-lock-alt'></i>
            </div>
            <div class="input-box">
                @Html.PasswordFor(m => m.ConfirmPass, new { @placeholder = "Nhập lại mật khẩu", @required = "required", @autocomplete = "confirm-password" })
                <i class='bx bxs-lock-alt'></i>
            </div>
            <div class="input-box">
                @Html.TextBoxFor(m => m.NgaySinh, new { @placeholder = "Nhập ngày sinh", @type = "date", @required = "required", @autocomplete = "bday", @style = "padding-right: 19px" })
            </div>
            <div class="input-box">
                @Html.TextBoxFor(m => m.DiaChi, new { @placeholder = "Nhập địa chỉ", @required = "required", @autocomplete = "address-line1" })
                <i class='bx bx-map'></i>
            </div>
            <div class="input-box">
                @Html.TextBoxFor(m => m.QuocTich, new { @placeholder = "Nhập quốc tịch", @required = "required", @autocomplete = "address-line1" })
                <i class='bx bx-map'></i>
            </div>
            <div class="input-box" style="display: flex; justify-content: center">
                @Html.RadioButtonFor(m => m.GioiTinh, true, new { @style = "width: 15px; height: 15px; vertical-align: middle; margin: 0 5px 0 0;" }) Nam
                @Html.RadioButtonFor(m => m.GioiTinh, false, new { @style = "width: 15px; height: 15px; vertical-align: middle; margin: 0 5px 0 5px;" }) Nữ
            </div>
            <div class="Dong_y_dieu_khoan">
                <label><input type="checkbox" id="terms" required />I agree all statements in <a href="#">Terms of service</a></label>
            </div>
            <button type="submit" value="Đăng Ký" class="btn_Dang_ky" id="registerButton">Đăng ký</button>
        }
    </div>

    <script>
        $(document).ready(function () {
            $('#registerButton').prop('disabled', true); // Disable button initially

            $('#terms').change(function () {
                if ($(this).is(':checked')) {
                    $('#registerButton').prop('disabled', false); // Enable button if checkbox is checked
                } else {
                    $('#registerButton').prop('disabled', true); // Disable button if checkbox is unchecked
                }
            });    
        });
    </script>
</body>
</html>

Web_Plane/Views/Chucnang/QuenMatKhau.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quên mật khẩu</title>
    <link href="~/Content/css/QuenMatKhauStyle.css" rel="stylesheet" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    <div class="wrapper">
        <form action="">
            <h1>Quên mật khẩu </h1>
            <div class="input-box">
                <input type="text" placeholder="Nhập tên đăng nhập" required />
                <i class='bx bxs-user'></i>
            </div>
            <div class="input-box">
                <input type="text" placeholder="Nhập mật khẩu mới" required />
                <i class='bx bxs-lock-alt'></i>
            </div>
            <div class="input-box">
                <input type="text" placeholder="Nhập lại mật khẩu mới" required />
                <i class='bx bxs-lock-alt' ></i>
            </div>
            <button type="submit" class="btn_Quen_mat_khau">Đổi mật khẩu</button>
            <div class="quay_lai_dang_nhap">
                <p> <a href="https://localhost:44380/ChucNang/DangNhap">Quay lại đăng nhập</a></p>
            </div>
        </form>
    </div>
</body>
</html>

Web_Plane/Views/Chucnang/ThongTinChuyenBay.cshtml
@model IEnumerable<Web_Plane.Models.CHUYENBAY>

@{
    ViewBag.Title = "ThongTinChuyenBay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ThongTinChuyenBay</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IDCB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LoaiChuyenBay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IDHK)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoCong)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IDCB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LoaiChuyenBay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IDHK)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoCong)
        </td>
        <td>
            @Html.ActionLink("Xem chi tiết", "CacVe", new { idcb = item.IDCB }) 
        </td>
    </tr>
}

</table>